export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  COD_PENDING_VERIFICATION = 'COD_PENDING_VERIFICATION',
  PROCESSING = 'PROCESSING',
  PACKED = 'PACKED',
  HANDED_OVER_TO_COURIER = 'HANDED_OVER_TO_COURIER',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RTO_INITIATED = 'RTO_INITIATED', // Return to Origin
  RTO_DELIVERED = 'RTO_DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum ReturnStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PICKUP_SCHEDULED = 'PICKUP_SCHEDULED',
  ITEM_RECEIVED = 'ITEM_RECEIVED',
  INSPECTION_PASSED = 'INSPECTION_PASSED',
  REFUND_ISSUED = 'REFUND_ISSUED',
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ON_HOLD = 'ON_HOLD',
}
