import crypto from 'crypto';
import axios from 'axios';
import { PrismaClient, PaymentGateway, PaymentStatus, OrderStatus } from '@prisma/client';

const prisma = new PrismaClient();

// Gateway Configuration
const ESEWA_PRODUCT_CODE = process.env.ESEWA_PRODUCT_CODE || 'EPAYTEST';
const ESEWA_SECRET_KEY = process.env.ESEWA_SECRET_KEY || '8gBm/:&EnhH.1/q';
const ESEWA_STATUS_CHECK_URL = process.env.ESEWA_STATUS_CHECK_URL || 'https://rc-epay.esewa.com.np/api/epay/transaction/status/';

const KHALTI_SECRET_KEY = process.env.KHALTI_SECRET_KEY || 'live_secret_key_6821360862b2434f81014e308910b427';
const KHALTI_LOOKUP_URL = process.env.KHALTI_LOOKUP_URL || 'https://khalti.com/api/v2/epayment/lookup/';

export interface EsewaSignaturePayload {
  total_amount: string;
  transaction_uuid: string;
  product_code: string;
}

export class PaymentService {
  /**
   * Generates eSewa 2.0 HMAC-SHA256 Signature
   * Signature is generated by hashing "total_amount,transaction_uuid,product_code" using secret key.
   */
  public static generateEsewaSignature(data: EsewaSignaturePayload): string {
    const message = `total_amount=${data.total_amount},transaction_uuid=${data.transaction_uuid},product_code=${data.product_code}`;
    const hmac = crypto.createHmac('sha256', ESEWA_SECRET_KEY);
    hmac.update(message);
    return hmac.digest('base64');
  }

  /**
   * Verifies eSewa Return Callback and completes Order
   */
  public static async verifyEsewaCallback(encodedData: string) {
    // 1. Decode base64 payload from eSewa redirect
    const decodedString = Buffer.from(encodedData, 'base64').toString('utf-8');
    const parsed = JSON.parse(decodedString);

    const {
      transaction_code,
      status,
      total_amount,
      transaction_uuid,
      product_code,
      signature: receivedSignature,
    } = parsed;

    if (status !== 'COMPLETE') {
      throw new Error(`ESEWA_TRANSACTION_FAILED: Status is ${status}`);
    }

    // 2. Validate HMAC Signature locally
    const expectedSignature = this.generateEsewaSignature({
      total_amount,
      transaction_uuid,
      product_code: product_code || ESEWA_PRODUCT_CODE,
    });

    if (expectedSignature !== receivedSignature) {
      throw new Error('SECURITY_ALERT: Esewa signature verification failed!');
    }

    // 3. Server-to-server transaction status query for double-verification
    const statusQueryUrl = `${ESEWA_STATUS_CHECK_URL}?product_code=${product_code || ESEWA_PRODUCT_CODE}&total_amount=${total_amount}&transaction_uuid=${transaction_uuid}`;
    const checkResponse = await axios.get(statusQueryUrl);

    if (checkResponse.data?.status !== 'COMPLETE') {
      throw new Error('ESEWA_SERVER_VERIFICATION_REJECTED');
    }

    // 4. Update Database inside an atomic transaction
    return await prisma.$transaction(async (tx) => {
      const paymentTx = await tx.paymentTransaction.findUnique({
        where: { transactionUuid: transaction_uuid },
        include: { order: true },
      });

      if (!paymentTx) {
        throw new Error('TRANSACTION_NOT_FOUND');
      }

      if (paymentTx.status === PaymentStatus.SUCCESS) {
        return { success: true, alreadyProcessed: true, orderId: paymentTx.orderId };
      }

      // Update payment record
      await tx.paymentTransaction.update({
        where: { id: paymentTx.id },
        data: {
          status: PaymentStatus.SUCCESS,
          gatewayReferenceId: transaction_code,
          verifiedAt: new Date(),
          gatewayResponse: checkResponse.data,
        },
      });

      // Update Order status
      const updatedOrder = await tx.order.update({
        where: { id: paymentTx.orderId },
        data: {
          orderStatus: OrderStatus.ORDER_PLACED,
        },
      });

      return {
        success: true,
        orderId: updatedOrder.id,
        orderNumber: updatedOrder.orderNumber,
        gatewayRefId: transaction_code,
      };
    });
  }

  /**
   * Verifies Khalti v2 EPAY Payment using server-to-server lookup
   */
  public static async verifyKhaltiPayment(pidx: string, transactionUuid: string) {
    // 1. Call Khalti lookup API with server secret key
    const lookupResponse = await axios.post(
      KHALTI_LOOKUP_URL,
      { pidx },
      {
        headers: {
          Authorization: `Key ${KHALTI_SECRET_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    const khaltiData = lookupResponse.data;

    if (khaltiData.status !== 'Completed') {
      throw new Error(`KHALTI_PAYMENT_UNSUCCESSFUL: Status is ${khaltiData.status}`);
    }

    // 2. Atomic Database Update
    return await prisma.$transaction(async (tx) => {
      const paymentTx = await tx.paymentTransaction.findUnique({
        where: { transactionUuid },
      });

      if (!paymentTx) {
        throw new Error('TRANSACTION_NOT_FOUND');
      }

      if (paymentTx.status === PaymentStatus.SUCCESS) {
        return { success: true, alreadyProcessed: true, orderId: paymentTx.orderId };
      }

      // Update Payment Transaction
      await tx.paymentTransaction.update({
        where: { id: paymentTx.id },
        data: {
          status: PaymentStatus.SUCCESS,
          gatewayReferenceId: khaltiData.transaction_id || pidx,
          verifiedAt: new Date(),
          gatewayResponse: khaltiData,
        },
      });

      // Update Order Status
      const order = await tx.order.update({
        where: { id: paymentTx.orderId },
        data: {
          orderStatus: OrderStatus.ORDER_PLACED,
        },
      });

      return {
        success: true,
        orderId: order.id,
        orderNumber: order.orderNumber,
        gatewayRefId: khaltiData.transaction_id || pidx,
      };
    });
  }
}
